//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product(string name, double price, short quantity)
        {
            Name = name;
            Price = price;
            Quantity = quantity;
        }
        public Product()
        {


        }
        public string Name { get; set; }
        public double Price { get; set; }
        public short Quantity { get; set; }
    }
}
